[33mcommit 744b32550844717eaee2c8273d689d49e5e099f0[m
Author: junseo Lee <74139368+juns0720@users.noreply.github.com>
Date:   Fri Jan 24 23:11:05 2025 +0900

    Delete src/main/resources/application.yml

[33mcommit 0eb78c37c77c753c16cda77d07352dc1c8d9e252[m[33m ([m[1;31morigin/feature/StudentRepository[m[33m, [m[1;32mfeature/StudentRepository[m[33m)[m
Author: Yithian01 <Yithian01@git.com>
Date:   Fri Jan 24 22:21:05 2025 +0900

    feat 학ì: Implement student registration with CSV upload
    
    - Created StudentService, StudentRepository, StudentProfileService, and StudentProfileRepository.
    - Implemented saveStudent and saveStudentProfile functions to handle student data processing.
    - Successfully added functionality to upload and store student data from a CSV file.
