version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-test
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-change-me}
      MYSQL_DATABASE: sku_graduation     # 원하는 DB명
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  spring:
    image: dbwlsdud/ghost-holiday
    container_name: ghost-holiday
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-test:3306/sku_graduation
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-change-me}
    restart: "no"

volumes:
  mysql_data:
