# JPA
spring:
  profiles:
    active: default
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: root
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false

s3:
  bucket: ${BUCKET_NAME}
  cloudfront-url: ${CLOUDFRONT_URL}


logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace